# Generated by Django 3.0.4 on 2020-03-21 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_song_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='notes',
        ),
    ]
