# Generated by Django 3.0.4 on 2020-03-21 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20200321_1727'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='soundFile',
            new_name='sound_file',
        ),
    ]
