# Generated by Django 3.0.4 on 2020-03-22 18:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20200322_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='note',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.RemoveField(
            model_name='song',
            name='notes',
        ),
        migrations.AddField(
            model_name='song',
            name='notes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='song',
            name='title',
            field=models.CharField(max_length=60, unique=True),
        ),
    ]
