# Generated by Django 3.0.4 on 2020-03-25 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20200324_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.FileField(null=True, upload_to='notes'),
        ),
    ]
