# Generated by Django 3.0.4 on 2020-03-25 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_song_song_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='song_file',
        ),
    ]
