# Generated by Django 3.0.4 on 2020-03-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_remove_song_song_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
