# Generated by Django 3.0.4 on 2020-04-02 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='time_stamp',
        ),
    ]
