# Generated by Django 3.0.4 on 2020-04-26 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0022_comment_time_stamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='sound_file',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
