# Generated by Django 3.0.4 on 2020-04-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0023_auto_20200426_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='sound',
            field=models.FileField(blank=True, null=True, upload_to='notes'),
        ),
    ]
